# https://circleci.com/docs/2.0/language-javascript/
version: 2
jobs:
  'node-12':
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: yarn install --frozen-lockfile
      - save_cache:
          paths:
            - ~/.cache/yarn
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn build
      # - run: yarn test
      # - run: yarn run cov:send
      # - run: yarn run cov:check

workflows:
  version: 2
  build:
    jobs:
      - 'node-12'
